export default Object.freeze({
    //GLOBAL TYPES
    SET_LOADING: 'SET_LOADING',
    SET_SUCCSSES_MESSAGE: 'SET_SUCCSSES_MESSAGE',
    SET_ERRORMESSAGE: 'SET_ERRORMESSAGE',

    //TODO TYPES
    RESET_TODO_STATE: 'RESET_STATE',
    OPEN_ADD_MODAL: 'OPEN_ADD_MODAL',
    CLOSE_MODAL: 'CLOSE_MODAL',
    OPEN_EDIT_TASK_MODAL: 'OPEN_EDIT_TASK_MODAL',
    ADD_TASK: 'ADD_TASK',
    GET_TASK: 'GET_TASK',
    //ADDMODAL TYPES
    HANDLE_CHANGE_MODAL: 'HANDLE_CHANGE_MODAL',
    ONCHANGE_DROPDOWN: 'ONCHANGE_DROPDOWN',

    //SORT
    SORT_DROPDOWN: 'SORT_DROPDOWN'
});